version: '2'

services:
  front:
    build: ./front
    restart: always
    ports:
     - "8000:8000"

  back:
    build: ./back
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    expose:
      - "27017"

volumes:
  db_data:
